name: Kubernetes Javascript Client - Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Remove specific version from 20 when https://github.com/tschaub/mock-fs/issues/380 is fixed
        node: [ '20.7.0', '18', '16' ]
    name: Node ${{ matrix.node }} validation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      # Pre-check to validate that versions match between package.json
      # and package-lock.json. Needs to run before npm install
      - run: node version-check.js
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm audit --audit-level=critical

